// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stream.proto

package rtsp

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Stream struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	URL                  string   `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
	CustomPath           string   `protobuf:"bytes,3,opt,name=CustomPath,proto3" json:"CustomPath,omitempty"`
	IdleTimeout          int64    `protobuf:"varint,4,opt,name=IdleTimeout,proto3" json:"IdleTimeout,omitempty"`
	HeartbeatInterval    int64    `protobuf:"varint,5,opt,name=HeartbeatInterval,proto3" json:"HeartbeatInterval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stream) Reset()         { *m = Stream{} }
func (m *Stream) String() string { return proto.CompactTextString(m) }
func (*Stream) ProtoMessage()    {}
func (*Stream) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb17ef3f514bfe54, []int{0}
}

func (m *Stream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stream.Unmarshal(m, b)
}
func (m *Stream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stream.Marshal(b, m, deterministic)
}
func (m *Stream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stream.Merge(m, src)
}
func (m *Stream) XXX_Size() int {
	return xxx_messageInfo_Stream.Size(m)
}
func (m *Stream) XXX_DiscardUnknown() {
	xxx_messageInfo_Stream.DiscardUnknown(m)
}

var xxx_messageInfo_Stream proto.InternalMessageInfo

func (m *Stream) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Stream) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *Stream) GetCustomPath() string {
	if m != nil {
		return m.CustomPath
	}
	return ""
}

func (m *Stream) GetIdleTimeout() int64 {
	if m != nil {
		return m.IdleTimeout
	}
	return 0
}

func (m *Stream) GetHeartbeatInterval() int64 {
	if m != nil {
		return m.HeartbeatInterval
	}
	return 0
}

func init() {
	proto.RegisterType((*Stream)(nil), "rtsp.Stream")
}

func init() { proto.RegisterFile("stream.proto", fileDescriptor_bb17ef3f514bfe54) }

var fileDescriptor_bb17ef3f514bfe54 = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x2e, 0x29, 0x4a,
	0x4d, 0xcc, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x29, 0x2a, 0x29, 0x2e, 0x50, 0x9a,
	0xc5, 0xc8, 0xc5, 0x16, 0x0c, 0x16, 0x16, 0xe2, 0xe3, 0x62, 0xf2, 0x74, 0x91, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x0c, 0x62, 0xf2, 0x74, 0x11, 0x12, 0xe0, 0x62, 0x0e, 0x0d, 0xf2, 0x91, 0x60, 0x02,
	0x0b, 0x80, 0x98, 0x42, 0x72, 0x5c, 0x5c, 0xce, 0xa5, 0xc5, 0x25, 0xf9, 0xb9, 0x01, 0x89, 0x25,
	0x19, 0x12, 0xcc, 0x60, 0x09, 0x24, 0x11, 0x21, 0x05, 0x2e, 0x6e, 0xcf, 0x94, 0x9c, 0xd4, 0x90,
	0xcc, 0xdc, 0xd4, 0xfc, 0xd2, 0x12, 0x09, 0x16, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0x64, 0x21, 0x21,
	0x1d, 0x2e, 0x41, 0x8f, 0xd4, 0xc4, 0xa2, 0x92, 0xa4, 0xd4, 0xc4, 0x12, 0xcf, 0xbc, 0x92, 0xd4,
	0xa2, 0xb2, 0xc4, 0x1c, 0x09, 0x56, 0xb0, 0x3a, 0x4c, 0x89, 0x24, 0x36, 0xb0, 0x4b, 0x8d, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x53, 0xe9, 0x01, 0xdb, 0xb9, 0x00, 0x00, 0x00,
}
