// Code generated by protoc-gen-go. DO NOT EDIT.
// source: record.proto

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Task struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PlayPath             string   `protobuf:"bytes,2,opt,name=PlayPath,proto3" json:"PlayPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Task) GetPlayPath() string {
	if m != nil {
		return m.PlayPath
	}
	return ""
}

type TaskExecute struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	TaskID               string   `protobuf:"bytes,2,opt,name=TaskID,proto3" json:"TaskID,omitempty"`
	SDPRaw               string   `protobuf:"bytes,3,opt,name=SDPRaw,proto3" json:"SDPRaw,omitempty"`
	StartTime            int64    `protobuf:"varint,4,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime              int64    `protobuf:"varint,5,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskExecute) Reset()         { *m = TaskExecute{} }
func (m *TaskExecute) String() string { return proto.CompactTextString(m) }
func (*TaskExecute) ProtoMessage()    {}
func (*TaskExecute) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{1}
}

func (m *TaskExecute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskExecute.Unmarshal(m, b)
}
func (m *TaskExecute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskExecute.Marshal(b, m, deterministic)
}
func (m *TaskExecute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskExecute.Merge(m, src)
}
func (m *TaskExecute) XXX_Size() int {
	return xxx_messageInfo_TaskExecute.Size(m)
}
func (m *TaskExecute) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskExecute.DiscardUnknown(m)
}

var xxx_messageInfo_TaskExecute proto.InternalMessageInfo

func (m *TaskExecute) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *TaskExecute) GetTaskID() string {
	if m != nil {
		return m.TaskID
	}
	return ""
}

func (m *TaskExecute) GetSDPRaw() string {
	if m != nil {
		return m.SDPRaw
	}
	return ""
}

func (m *TaskExecute) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *TaskExecute) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

type Block struct {
	ID                   int64        `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	TaskExecute          *TaskExecute `protobuf:"bytes,2,opt,name=TaskExecute,proto3" json:"TaskExecute,omitempty"`
	StartTime            int64        `protobuf:"varint,3,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime              int64        `protobuf:"varint,4,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	Size                 int32        `protobuf:"varint,5,opt,name=Size,proto3" json:"Size,omitempty"`
	Data                 []byte       `protobuf:"bytes,6,opt,name=Data,proto3" json:"Data,omitempty"`
	Path                 string       `protobuf:"bytes,7,opt,name=Path,proto3" json:"Path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{2}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Block) GetTaskExecute() *TaskExecute {
	if m != nil {
		return m.TaskExecute
	}
	return nil
}

func (m *Block) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Block) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *Block) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Block) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Block) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func init() {
	proto.RegisterType((*Task)(nil), "models.Task")
	proto.RegisterType((*TaskExecute)(nil), "models.TaskExecute")
	proto.RegisterType((*Block)(nil), "models.Block")
}

func init() { proto.RegisterFile("record.proto", fileDescriptor_bf94fd919e302a1d) }

var fileDescriptor_bf94fd919e302a1d = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4a, 0x4d, 0xce,
	0x2f, 0x4a, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcb, 0xcd, 0x4f, 0x49, 0xcd, 0x29,
	0x56, 0x32, 0xe2, 0x62, 0x09, 0x49, 0x2c, 0xce, 0x16, 0xe2, 0xe3, 0x62, 0xf2, 0x74, 0x91, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xf2, 0x74, 0x11, 0x92, 0xe2, 0xe2, 0x08, 0xc8, 0x49, 0xac,
	0x0c, 0x48, 0x2c, 0xc9, 0x90, 0x60, 0x02, 0x8b, 0xc2, 0xf9, 0x4a, 0xad, 0x8c, 0x5c, 0xdc, 0x20,
	0x4d, 0xae, 0x15, 0xa9, 0xc9, 0xa5, 0x25, 0xa9, 0x48, 0x7a, 0x99, 0xc1, 0x7a, 0xc5, 0xb8, 0xd8,
	0x40, 0xd2, 0x9e, 0x2e, 0x50, 0x9d, 0x50, 0x1e, 0x48, 0x3c, 0xd8, 0x25, 0x20, 0x28, 0xb1, 0x5c,
	0x82, 0x19, 0x22, 0x0e, 0xe1, 0x09, 0xc9, 0x70, 0x71, 0x06, 0x97, 0x24, 0x16, 0x95, 0x84, 0x64,
	0xe6, 0xa6, 0x4a, 0xb0, 0x80, 0x8d, 0x41, 0x08, 0x08, 0x49, 0x70, 0xb1, 0xbb, 0xe6, 0xa5, 0x80,
	0xe5, 0x58, 0xc1, 0x72, 0x30, 0xae, 0xd2, 0x21, 0x46, 0x2e, 0x56, 0xa7, 0x9c, 0xfc, 0xe4, 0x6c,
	0x0c, 0x17, 0x98, 0xa2, 0x38, 0x10, 0xec, 0x0c, 0x6e, 0x23, 0x61, 0x3d, 0x88, 0x9f, 0xf5, 0x90,
	0xa4, 0x82, 0x50, 0x3c, 0x82, 0xe2, 0x10, 0x66, 0x3c, 0x0e, 0x61, 0x41, 0x71, 0x88, 0x90, 0x10,
	0x17, 0x4b, 0x70, 0x66, 0x15, 0xc4, 0x7d, 0xac, 0x41, 0x60, 0x36, 0x48, 0xcc, 0x25, 0xb1, 0x24,
	0x51, 0x82, 0x4d, 0x81, 0x51, 0x83, 0x27, 0x08, 0xcc, 0x06, 0x89, 0x81, 0x03, 0x94, 0x1d, 0xec,
	0x7d, 0x30, 0x3b, 0x89, 0x0d, 0x1c, 0x1f, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd8, 0xc3,
	0xab, 0x2d, 0x9f, 0x01, 0x00, 0x00,
}
